final Map<String, String> carrierCodeNameMap = {
  'IX': 'AirIndia Express',
  'SQ': 'Singapore Airlines',
  'UK': 'Vistara',
  '6E': 'IndiGo',
  'I5': 'AirIndia Express',
  'AI': 'Air India',
  'QP': 'Akasa Air',
  'SG': 'SpiceJet',
  'H1': 'Hahn Air',
  'X1': 'Hahn Air',
  'EK': 'Emirates',
  'VS': 'Virgin Atlantic',
  'CX': 'Cathay Pacific',
  'LX': 'Swiss International Air Lines',
  'EY': 'Etihad Airways',
  'UA': 'United',
  'TK': 'Turkish Airlines',
  'SV': 'Saudia',
  'SK': 'SAS',
  'QR': 'Qatar Airways',
  'AY': 'Finnair',
  'MS': 'Egypt Air',
  'ET': 'Ethiopian Air',
  'WY': 'Oman Av (SAOG)',
  'BA': 'British Airways',
  'GF': 'Gulf Air',
  'LH': 'Lufthansa',
  'KC': 'Air Astana',
  'EN': 'Air Dolomiti',
  'KL': 'KLM Royal Dutch Airlines',
  'AF': 'Air France',
  'AZ': 'ITA Airways',
  'KU': 'Kuwait Airways',
  'TG': 'Thai Airways',
  'DL': 'Delta',
  'NH': 'All Nippon',
  'AC': 'Air Canada',
  'LO': 'LOT Polish Air',
  'UL': 'SriLankan Airlines',
  'G9': 'Air Arabia',
  'XY': 'Flynas',
  'FZ': 'flydubai',
  'HY': 'Uzbekistan',
  'BG': 'Biman Bangladesh',
  '9I': 'Alliance Air',
  'S5': 'Star Air',
  'QF': 'Qantas',
  'VJ': 'Vietjet Air',
  'VN': 'Vietnam Airlines',
  'MH': 'Malaysia Airlines',
  'OD': 'Malindo Air',
  'AS': 'Alaska Airlines',
  'MK': 'Air Mauritius',
  'OZ': 'Asiana Airlines',
  'KP': 'Asky Airlines',
};
